#ifndef  _EVENT_DISPACHER_TYPE_H
#define  _EVENT_DISPACHER_TYPE_H
#include<iostream>

typedef enum //自动搜索方式
{
	//UI events enum start after end of muf core events.
	ENUM_UI_EVENT_START = 0x20000000 + 1,

	///MM Events
	ENUM_MM_EVENT_START = ENUM_UI_EVENT_START + 1,

	ENUM_MMPLAYER,
	ENUM_MEDIA_BROWSER,
	ENUM_MEDIA_SUBTITLE_PARSER,
	ENUM_MEDIA_FILE_PLAYER,
	ENUM_MEDIA_THUMBNAIL,
	ENUM_MEDIA_DEVICE,
	ENUM_MEDIA_SUBTITLE,
	ENUM_MEDIA_TEXT,


	///TV Events
	ENUM_TV_EVENT_START = ENUM_UI_EVENT_START + 0x00001000,

	ENUM_ATVPLAYER,
	ENUM_ATV_AUTO_TUNING_SCAN_INFO,
	ENUM_ATV_MANUAL_TUNING_SCAN_INFO,

	ENUM_DTVPLAYER,
	ENUM_DTV_AUTO_TUNING_SCAN_INFO,
	ENUM_DTV_MANUAL_TUNING_SCAN_INFO,
	ENUM_CLOSE_SUBTITLE_ACK,
	ENUM_AUTO_TUNING_TYPE,
	ENUM_DTV_READY_POPUP_DIALOG,
	ENUM_DTV_CHANNELNAME_READY,
	ENUM_DTV_PROGRAM_INFO_READY,
	ENUM_DTV_LCN_CONFLICT,
	ENUM_DTV_PRI_COMPONENT_MISSING,
	ENUM_DTV_AUTO_UPDATE_SCAN,

	ENUM_DTV_CHANNEL_CHANGE,
	ENUM_INPUTSOURCE_CHANGE,

	ENUM_DTV_CHANNEL_INFO_UPDATE,
	ENUM_DESTROY_COUNTDOWN,
	ENUM_ONESECOND_BEAT,
	ENUM_LASTMINUTE_WARN,
	ENUM_UPDATE_LASTMINUTE,
	ENUM_SIGNAL_UNLOCK,
	ENUM_SIGNAL_LOCK,
	ENUM_TS_CHANGE,
	ENUM_POPUP_DIALOG,
	ENUM_SCREEN_SAVER_MODE,
	ENUM_TIMER_SYSTEM_CLK_CHG,

	ENUM_DTV_SGT_SCAN_LCN_LISTS_READY,
	ENUM_DTV_ASTRA_NEW_SERVICE,

	ENUM_DTV_EMERGENCY_ALERT,
	ENUM_TIMER_TIME_ZONE_CHG,
	ENUM_INPUT_SOURCE_LOCK,
	ENUM_SIGNAL_UNSTABLE,

#if (DLNA_DMPDMR == 0 && DLNA_DMPONLY == 0)

	///DLNA Events
	ENUM_DLNA_EVENT_START = ENUM_UI_EVENT_START + 0x00002000,

	ENUM_DLNA_MOVIE,
	ENUM_DLNA_MUSIC,
	ENUM_DLNA_PHOTO,
	ENUM_DLNA_NETWORK,
	ENUM_DLNA_DMR_MOVIE,
	ENUM_DLNA_DMR_MUSIC,
	ENUM_DLNA_DMR_PHOTO,
	ENUM_DLNA_DMR_NETWORK,
	ENUM_DMP_QUIT,
#endif


	///EPG Events
	ENUM_EPG_EVENT_START = ENUM_UI_EVENT_START + 0x00003000,

	ENUM_EPG_UPDATE_LASTMINUTE,
	ENUM_EPG_UPDATE_LIST,
	ENUM_EPGTIMER_COUNTDOWN,
	ENUM_EPGTIMER_RECORD_START,
	ENUM_EPGTIMER_SIMULCAST,
	ENUM_EPG_NOTIFY_CI_PLUS_CAM_PINCODE,
	ENUM_EPG_UPDATE_FINISH,
	ENUM_EPG_REFRESH_NOTIFY,

	///PVR Events
	ENUM_PVR_EVENT_START = ENUM_UI_EVENT_START + 0x00004000,

	ENUM_PVR_NOTIFY_PLAYBACK_TIME,
	ENUM_PVR_NOTIFY_PLAYBACK_SPEED_CHANGE,
	ENUM_PVR_NOTIFY_RECORD_TIME,
	ENUM_PVR_NOTIFY_RECORD_SIZE,
	ENUM_PVR_NOTIFY_TOTAL_TIME,
	ENUM_PVR_NOTIFY_RECORD_STOP,
	ENUM_PVR_NOTIFY_PLAYBACK_STOP,
	ENUM_PVR_NOTIFY_PLAYBACK_BEGIN,
	ENUM_PVR_NOTIFY_TIMESHIFT_STOP,
	ENUM_PVR_NOTIFY_TIMESHIFT_OVERWRITES_BEFORE,
	ENUM_PVR_NOTIFY_TIMESHIFT_OVERWRITES_AFTER,
	ENUM_PVR_NOTIFY_OVER_RUN,
	ENUM_PVR_NOTIFY_USB_INSERTED,
	ENUM_PVR_NOTIFY_USB_REMOVED,
	ENUM_PVR_NOTIFY_FORMAT_FINISHED,
	ENUM_PVR_NOTIFY_CI_PLUS_PROTECTION,
	ENUM_PVR_NOTIFY_CI_PLUS_RETENTION_LIMIT_UPDATE,
	ENUM_PVR_NOTIFY_CI_PLUS_RETENTION_LIMIT_EXPIRED,
	ENUM_PVR_NOTIFY_CI_PLUS_CAM_PINCODE,
	ENUM_PVR_NOTIFY_USB_MOUNTED,
	ENUM_PVR_NOTIFY_PARENTAL_CONTROL,
	ENUM_PVR_NOTIFY_SCHEDULED_STOP,

	ENUM_PVR_NOTIFY_RECORD_START,
	ENUM_PVR_NOTIFY_WRITE_FILE_FAIL,
	ENUM_PVR_NOTIFY_BOOK_RECORD_STOP,
	ENUM_PVR_NOTIFY_USB_REMOVE_FINISHED,
	ENUM_PVR_NOTIFY_COPY_FINISHED,
	ENUM_PVR_NOTIFY_COPY_FAIL,
	ENUM_PVR_NOTIFY_PARENTAL_RATING,
	ENUM_PVR_NOTIFY_TS_CHANGE,
	ENUM_PVR_NOTIFY_TS_CHANGE_SHOW,
	ENUM_PVR_NOTIFY_UPDATE_CHANNEL_LIST,
	ENUM_PVR_NOTIFY_RECORD_OUTOF_SPACE,
	ENUM_PVR_NOTIFY_PLAYBACK_JUMP_REACHSYNC,
	ENUM_PVR_NOTIFY_ALWAYS_TIMESHIFT_PROGRAM_READY,   //for ATshift
	ENUM_PVR_NOTIFY_ALWAYS_TIMESHIFT_PROGRAM_NOTREADY,    //for ATshift
	ENUM_PVR_RECORD_FOREGROUND_TO_BACKGROUND,
	ENUM_PVR_RECORD_BACKGROUND_TO_FOREGROUND,
	ENUM_PVR_UPDATE_RECORD_ICON_STATUS,
	ENUM_PVR_NOTIFY_CHANNEL_CHANGE_UNSUPPORT,

	///CIMMI Events
	ENUM_CIMMI_EVENT_START = ENUM_UI_EVENT_START + 0x00005000,

	ENUM_CIMMI_UI_DATA_READY,
	ENUM_CIMMI_UI_ENQ,
	ENUM_CIMMI_UI_CLOSEMMI,
	ENUM_CIMMI_UI_CARD_INSERTED,
	ENUM_CIMMI_UI_CARD_REMOVED,
	ENUM_CIMMI_UI_NO_MODULE,
	ENUM_CIMMI_UI_TRY_AGAIN,
	ENUM_CIMMI_UI_OPEN_MENU,
	ENUM_CIMMI_UI_AUTOTEST_MESSAGE_SHOWN,
	ENUM_CIMMI_UI_CLEAR_AUTOTEST_LOG_FILE,
	ENUM_CIPLUS_CU_START,
	ENUM_CIPLUS_CU_PROGRESS,
	ENUM_CIPLUS_CU_COMPLETE,
	ENUM_CI_LOAD_CREDENTIAL_FAIL,
	ENUM_CIPLUS_OPERATORING_MODE_CHECK,
	ENUM_CIPLUS_KEY_VIA_USB_UPDATE,
	ENUM_CIPLUS_OP_REFRESH_QUERY,
	ENUM_CIPLUS_OP_REFRESH_URGENT,
	ENUM_CIPLUS_END_OF_OP_SEARCH,
	ENUM_CIPLUS_CANCEL_OP_SEARCH,
	ENUM_CIPLUS_PROGRESS_OP_SEARCH,
	ENUM_CI_OCCUPIED_TUNER,

	///key event for virtual keyboard
	ENUM_KEYINPUT_EVENT_START = ENUM_UI_EVENT_START + 0x00006000,
	ENUM_KEYIN_BACKSPACE,
	ENUM_KEYIN_LOADURL,
	ENUM_KEYIN_DONE,
	ENUM_KEYIN_CUT,
	ENUM_KEYIN_PASTE,
	ENUM_KEYIN_LEFT,
	ENUM_KEYIN_RIGHT,
	ENUM_KEYIN_DOWN,
	ENUM_KEYIN_UP,
	ENUM_KEYIN_HOME,
	ENUM_KEYIN_END,


	ENUM_OTHER_UI_EVENT_START = ENUM_UI_EVENT_START + 0x00010000,

	ENUM_SCARTMUTE_OSD_MODE,
	ENUM_DUAL_MONO_STATUS,
	ENUM_MENU_OPEN_PAGE,
	///to post event av sync done or timeout
	ENUM_AV_SYNC_DONE,
	ENUM_AV_SYNC_TIMEOUT,
	ENUM_SETVOLUME_UI_EVENT,
	ENUM_AP_SETVOLUME_EVENT,
	ENUM_RCT_PRESENCE,
	ENUM_RCT_ABSENCE,
	ENUM_RCT_REFLESH,
	///notify audio mode change
	ENUM_AUDIO_MODE_CHANGE,

	///Network upgrade
	ENUM_NETWORK_UPDATE_STATUS,
	ENUM_NETWORK_STATUS,
	ENUM_NETWORK_UPDATE_DOWNLOAD_CONFIRM_DIALOG,
	ENUM_CHOOSE_RECORD_TO_STOP,

	ENUM_CHANGE_TTX_STATUS,

	ENUM_MHEG5_EVENT_HANDLER,
	ENUM_MHEG5_RETURN_KEY,
	ENUM_MHEG5_STATUS_MODE,

	ENUM_BCTI_MAPIPROCESS,
	ENUM_BCTI_STARTPLAYMOVIE,
	ENUM_BCTI_IMAGEPROCESS,
	ENUM_OAD_HANDLER,
	ENUM_OAD_DOWNLOAD,
	ENUM_OAD_SCANFINISH,
	ENUM_OAD_TIMEOUT,
	ENUM_OAD_TIMESCAN,

	ENUM_POPUP_SCAN_DIALOGE_LOSS_SIGNAL,
	ENUM_POPUP_SCAN_DIALOGE_NEW_MULTIPLEX,
	ENUM_POPUP_SCAN_DIALOGE_FREQUENCY_CHANGE,
	ENUM_POPUP_SCAN_DIALOGE_MULTIPLEX_REMOVED,
	ENUM_AUTO_TEST_DUMP,
	ENUM_IDLE_OPEN_MSG,
	ENUM_IDLE_CLOSE_MSG,
	ENUM_MANUAL_CLOSE_MSG,

	ENUM_HBBTV_UI_EVENT,

	//MStreamer
	ENUM_MSTREAMER_PLAYER,

	// add this to show menu in idleframe through ipc
	ENUM_NOTIFY_EXTERNED_UI,
	ENUM_NOTIFY_IPC_MESSAGE,
	//show right top textbox content (Galaxy Browser)
	ENUM_SHOW_RIGHTTEXT,

	ENUM_MOUNT_NOTIFIER,

	ENUM_PQ_SETTING_VIA_USB_UPDATE,
	ENUM_HDCP_KEY_VIA_USB_UPDATE,

	ENUM_INPUTSOURCE_UPDATED,

	//for multiprocess : SendEvent, PostEvent with wParam or lParam as struct
	ENUM_MULTIPROCESS_PASSEVENT_WITH_STRUCT,

	ENUM_HBBTV_STATUS_MODE,

	ENUM_GINGA_STATUS_MODE,

	ENUM_3D_MGR_NOTIFY,

	// No more used. If OSD timing change, call MUF UpdateLayerScreen directly.
	ENUM_OSD_CHANGE_OUTPUT_TIMING,

	ENUM_CEC_EVENT_START = ENUM_UI_EVENT_START + 0x00011000,

	//CEC Events
	ENUM_CEC_SOURCE_SWITCH,
	ENUM_CEC_DEVICE_POWER_ON,
	ENUM_CEC_DEVICE_STATUS_CHANGED,
	ENUM_CEC_DEVICE_DISCOVER_FINISHED,
	ENUM_CEC_OSD_MSG,
	ENUM_CEC_IMAGE_VIEW_ON,
	ENUM_CEC_TEXT_VIEW_ON,
	ENUM_CEC_HANDLER,
	ENUM_CEC_STANDBY,
	ENUM_CEC_SET_MENU_LANGUAGE,
	ENUM_CEC_SET_MENU_STATUS,
	ENUM_CEC_SEL_DIGITAL_SERVICE_ARIB,
	ENUM_CEC_SEL_DIGITAL_SERVICE_ATSC,
	ENUM_CEC_SEL_DIGITAL_SERVICE_DVB,
	ENUM_CEC_SEL_DIGITAL_SERVICE_CHANNEL_DATA,
	ENUM_CEC_POP_AMP_CONNECT,
	ENUM_CEC_UPDATE_EDID,

	ENUM_OTHER_EVENT_START = ENUM_UI_EVENT_START + 0x00012000,

	ENUM_MACAddr_VIA_USB_UPDATE,
	ENUM_SYSTEM_ASYNC_CMD,

	ENUM_TIMER_POWOER_EVENT,
	ENUM_TVOS_UTIITY_EVENT,

	ENUM_CA_SHOWBUYMESSAGE,
	ENUM_CA_SHOWFINGERMESSAGE,
	ENUM_CA_SHOWPROGRESSSTRIP,
	ENUM_CA_ACTIONREQUEST,
	ENUM_CA_ENTITLECHANGED,
	ENUM_CA_DETITLERECEIVED,
	ENUM_CA_STARTIPPVBUYDLG,
	ENUM_CA_HIDEIPPVDLG,
	ENUM_CA_EMAILNOTIFYICON,
	ENUM_CA_SHOWOSDMESSAGE,
	ENUM_CA_HIDEOSDMESSAGE,
	ENUM_CA_REQUESTFEEDING,
	ENUM_CA_LOCKSERVICE,
	ENUM_CA_UNLOCKSERVICE,
	ENUM_CA_OTASTATE,
	ENUM_CA_HIDEPROMPTMESSAGE,
	ENUM_CA_SHOWPROMPTMESSAGE,
	ENUM_CA_URGENCYBROADCAST,
	ENUM_CA_CANCELURGENCYBROADCAST,

	ENUM_IPC_EVENT,

	ENUM_OPSERVICE_LIST,
	ENUM_EXIT_OPSERVICE_LIST,

	ENUM_AUDIO_MUTE,
	ENUM_DMP_UI,
	ENUM_MESSAGEBOX_YES, /// Notified when MessageBoxFrame was selected YES.
	ENUM_MESSAGEBOX_NO,  /// Notified when MessageBoxFrame was selected NO.

	ENUM_POPUP_SCAN_DIALOGE_FULL_RESCAN,
	ENUM_NOTIFY_NETWORK_CHANGE_INFO,

	ENUM_NETREADY_EVENT_START = ENUM_UI_EVENT_START + 0x00013000,
	ENUM_NETREADY_USERCHECKFORUSB,
	ENUM_NETREADY_USERCHECKFORNET,
	ENUM_NETREADY_DOWNLOADCOMPLETE,
	ENUM_NETREADY_DEVICEAGENTERRORCODE,
	ENUM_NETREADY_SOFTWAREISUPTODATE,

	///Bluetooth events
	ENUM_NETWORK_BLUETOOTH = ENUM_UI_EVENT_START + 0x00014000,
	ENUM_NETWORK_BLUETOOTH_POWER_ON,
	ENUM_NETWORK_BLUETOOTH_UNPAIR,
	ENUM_NETWORK_BLUETOOTH_SCAN_RESULT,
	ENUM_NETWORK_BLUETOOTH_CONNECT_RESULT,
	ENUM_NETWORK_BLUETOOTH_UPDATE_PAIRED_DEVICE,
	ENUM_NETWORK_BLUETOOTH_UPDATE_CONNECTED_DEVICE,
	ENUM_NETWORK_BLUETOOTH_FINALIZED,

	ENUM_NETWORK_CONTROL = 0xA0000000 - 1000,

	ENUM_4K2K_HDMI_DISABLE_PIP,
	ENUM_4K2K_HDMI_DISABLE_POP,
	ENUM_4K2K_HDMI_DISABLE_DUALVIEW,
	ENUM_4K2K_HDMI_DISABLE_TRAVELINGMODE,

	ENUM_ENABLE_3D,
	ENUM_4K2K_UNSUPPORT_DUALVIEW,

	ENUM_INPUT_SOURCE_CONFLICT,

	ENUM_MHL_RECEIVE_RCP,
	ENUM_MHL_AUTO_SWITCH,

	ENUM_MESSAGEBOX_NOTIFY_CIHCRELEASE_YES,
	ENUM_MESSAGEBOX_NOTIFY_CIHCRELEASE_NO,

	ENUM_4K2K_STRETCH_WINDOW,
	ENUM_SET_SYS_PROPERTY_DESK_DISPLAY_MODE,
	ENUM_SET_SYS_PROPERTY_ENABLE_HWCURSOR,

	ENUM_PVR_NOTIFY_WARB_CONFLICT,
	ENUM_CA_SHOWCURTAINNOTIFY,
	ENUM_CA_CARDDETECT,
	ENUM_CA_AREALOCKOK,
	ENUM_CA_SWITCHCHANNEL,
	ENUM_PVR_NOTIFY_RECORD_POWERON_RESTART,

	ENUM_REFRESH_PREVIEW_MODE_WINDOW,

	///PVR Events
	ENUM_TRIGGER_RECORD_START_BY_PVRFRAME,

	ENUM_CONFIRM_KDG_LCN_UPDATE,

	ENUM_SET_UPGRADE_STATE,

	ENUM_NOTIFY_POWER_OFF,

	ENUM_SET_SYS_PROPERTY_RESOLUTION_STATE,

	ENUM_RVU_CLIENT_NOTIFY,

	ENUM_WIFI_P2P,

	ENUM_WIDI,

	ENUM_SET_SYS_PROPERTY_4K2K_ENABLE,
	ENUM_NETWORK_NOT_AVAILABLE,
	/// emergency system display
	ENUM_DISPLAY_EMERGENCY_SYSTEM,
	/// emergency system close
	ENUM_CLOSE_EMERGENCY_SYSTEM,
	/// detect 3D format
	ENUM_DETECT_3D_FORMAT,
	/// factorty dtv program finished
	ENUM_TV_FACTORYPROGRAM_FINISHED,
	ENUM_UI_EVENT_END = 0xA0000000,
}EventType;
//typedef void(*EventCallBack)(EventType  EventType_Data,void*param1,void*ptr);
typedef void(*EventCallBack)(EventType  EventType_Data,void*param1);
#endif