//<MStar Software>
/**********************************************************************
 Copyright (c) 2006-2009 MStar Semiconductor, Inc.
 All rights reserved.

 Unless otherwise stipulated in writing, any and all information contained
 herein regardless in any format shall remain the sole proprietary of
 MStar Semiconductor Inc. and be kept in strict confidence
 (MStar Confidential Information) by the recipient.
 Any unauthorized act including without limitation unauthorized disclosure,
 copying, use, reproduction, sale, distribution, modification, disassembling,
 reverse engineering and compiling of the contents of MStar Confidential
 Information is unlawful and strictly prohibited. MStar hereby reserves the
 rights to any and all damages, losses, costs and expenses resulting therefrom.

* File  : mapi_types.h
**********************************************************************/

#ifndef __MAPI_TYPES_H__
#define __MAPI_TYPES_H__

typedef unsigned char       MAPI_BYTE;  // 1 byte
typedef unsigned char       MAPI_BOOL;  // 1 byte

typedef signed char         MAPI_S8;    // 1 byte
typedef signed short        MAPI_S16;   // 2 bytes
typedef signed long         MAPI_S32;   // 4 bytes
typedef signed long long    MAPI_S64;   // 8 bytes

typedef unsigned char       MAPI_U8;    // 1 byte
typedef unsigned short      MAPI_U16;   // 2 bytes
typedef unsigned long       MAPI_U32;   // 4 bytes
typedef unsigned long long  MAPI_U64;   // 8 bytes

typedef unsigned short      MAPI_WORD;  // 2 bytes

typedef float              MAPI_FLOAT; // 4 bytes

/// Font handle, handle to font table in memory
typedef signed char FONTHANDLE;
/// Bitmap handle, handle to bitmap buffer
typedef signed short BMPHANDLE;
/// definition for DBHANDLE
typedef signed char  DBHANDLE;

#ifdef WIN32
typedef unsigned char uint8_t;
typedef  signed short int16_t;
typedef  unsigned short uint16_t;
typedef  signed int int32_t;
typedef unsigned int uint32_t;
#endif

///U8  maximal
#define U8_MAX                  (0xFF)
///U16 maximal
#define U16_MAX                 (0xFFFF)
///U32 maximal
#define U32_MAX                 (0xFFFFFFFFUL)

/// the input source type
typedef enum
{
    MAPI_INPUT_SOURCE_VGA,          ///<VGA input     0
    MAPI_INPUT_SOURCE_ATV,          ///<TV input      1

    MAPI_INPUT_SOURCE_CVBS,         ///<AV 1           2
    MAPI_INPUT_SOURCE_CVBS2,        ///<AV 2           3
    MAPI_INPUT_SOURCE_CVBS3,        ///<AV 3           4
    MAPI_INPUT_SOURCE_CVBS4,        ///<AV 4           5
    MAPI_INPUT_SOURCE_CVBS5,        ///<AV 5           6
    MAPI_INPUT_SOURCE_CVBS6,        ///<AV 6           7
    MAPI_INPUT_SOURCE_CVBS7,        ///<AV 7           8
    MAPI_INPUT_SOURCE_CVBS8,        ///<AV 8           9
    MAPI_INPUT_SOURCE_CVBS_MAX,     ///<AV max         10

    MAPI_INPUT_SOURCE_SVIDEO,       ///<S-video 1      11
    MAPI_INPUT_SOURCE_SVIDEO2,      ///<S-video 2      12
    MAPI_INPUT_SOURCE_SVIDEO3,      ///<S-video 3      13
    MAPI_INPUT_SOURCE_SVIDEO4,      ///<S-video 4      14
    MAPI_INPUT_SOURCE_SVIDEO_MAX,   ///<S-video max    15

    MAPI_INPUT_SOURCE_YPBPR,        ///<Component 1    16
    MAPI_INPUT_SOURCE_YPBPR2,       ///<Component 2    17
    MAPI_INPUT_SOURCE_YPBPR3,       ///<Component 3    18
    MAPI_INPUT_SOURCE_YPBPR_MAX,    ///<Component max   19

    MAPI_INPUT_SOURCE_SCART,        ///<Scart 1         20
    MAPI_INPUT_SOURCE_SCART2,       ///<Scart 2         21
    MAPI_INPUT_SOURCE_SCART_MAX,    ///<Scart max       22

    MAPI_INPUT_SOURCE_HDMI,         ///<HDMI 1          23
    MAPI_INPUT_SOURCE_HDMI2,        ///<HDMI 2          24
    MAPI_INPUT_SOURCE_HDMI3,        ///<HDMI 3          25
    MAPI_INPUT_SOURCE_HDMI4,        ///<HDMI 4          26
    MAPI_INPUT_SOURCE_HDMI_MAX,     ///<HDMI max         27

    MAPI_INPUT_SOURCE_DTV,          ///<DTV              28

    MAPI_INPUT_SOURCE_DVI,          ///<DVI 1            29
    MAPI_INPUT_SOURCE_DVI2,         ///<DVI 2            30
    MAPI_INPUT_SOURCE_DVI3,         ///<DVI 2            31
    MAPI_INPUT_SOURCE_DVI4,         ///<DVI 4            32
    MAPI_INPUT_SOURCE_DVI_MAX,      ///<DVI max          33

    // Application source
    MAPI_INPUT_SOURCE_STORAGE,  ///<Storage              34
    MAPI_INPUT_SOURCE_KTV,      ///<KTV                  35
    MAPI_INPUT_SOURCE_JPEG,     ///<JPEG                 36
    MAPI_INPUT_SOURCE_DTV2,      ///<DTV2                37
    MAPI_INPUT_SOURCE_STORAGE2,     ///<Storage2          38
    MAPI_INPUT_SOURCE_DTV3,      ///<DTV3                 39
    MAPI_INPUT_SOURCE_SCALER_OP, ///< video from op        40
    MAPI_INPUT_SOURCE_RVU,          ///<RVU            41
    MAPI_INPUT_SOURCE_VGA2,         ///<VGA2 input       42
    MAPI_INPUT_SOURCE_VGA3,         ///<VGA3 input       43
    MAPI_INPUT_SOURCE_GOOGLE_CAST,  ///<Google Cast      44
    MAPI_INPUT_SOURCE_NUM,      ///<number of the source   45
    MAPI_INPUT_SOURCE_NONE = MAPI_INPUT_SOURCE_NUM,    ///<NULL input
} MAPI_INPUT_SOURCE_TYPE;

typedef enum
{
    E_AUSTRALIA,                    ///< Australia
    E_AUSTRIA,                      ///< Austria
    E_BELGIUM,                      ///< Belgium
    E_BULGARIA,                     ///< Bulgaria
    E_CROATIA,                      ///< Croatia
    E_CZECH,                        ///< Czech
    E_DENMARK,                      ///< Denmark
    E_FINLAND,                      ///< Finland
    E_FRANCE,                       ///< France
    E_GERMANY,                      ///< Germany
    E_GREECE,                       ///< Greece
    E_HUNGARY,                      ///< Hungary
    E_ITALY,                        ///< Italy
    E_LUXEMBOURG,                   ///< Luxembourg
    E_NETHERLANDS,                  ///< Netherland
    E_NORWAY,                       ///< Norway
    E_POLAND,                       ///< Poland
    E_PORTUGAL,                     ///< Portugal
    E_RUMANIA,                      ///< Rumania
    E_RUSSIA,                       ///< Russia
    E_SERBIA,                       ///< Serbia
    E_SLOVENIA,                     ///< Slovenia
    E_SPAIN,                        ///< Spain
    E_SWEDEN,                       ///< Sweden
    E_SWITZERLAND,                  ///< Switzerland
    E_UK,                           ///< UK
    E_NEWZEALAND,                   ///< New Zealand
    E_ARAB,                         ///< Arab
    E_ESTONIA,                      ///< Estonia
    E_HEBREW,                       ///< Hebrew
    E_LATVIA,                       ///< Latvia
    E_SLOVAKIA,                     ///< Slovakia
    E_TURKEY,                       ///< Turkey
    E_IRELAND,                      ///< Ireland
    E_JAPAN,                         ///<Japan
    E_PHILIPPINES,             ///<Philippines
    E_THAILAND,                ///<Thailand
    E_MALDIVES,                 ///<Maldives
    E_URUGUAY,                  ///<Uruguay
    E_PERU,                            ///<Peru
    E_ARGENTINA,                 ///<Argentina
    E_CHILE,                           ///<Chile
    E_VENEZUELA,                ///Venezuela
    E_ECUADOR,                     ///<Ecuador
    E_COSTARICA,                 ///<Costarica
    E_PARAGUAY,                    ///<Paraguay
    E_BOLIVIA,                      ///<Bolivia
    E_BELIZE,                          ///<Belize
    E_NICARAGUA,                  ///<Nicaragua
    E_GUATEMALA,                 ///<Guatemala
    E_CHINA,                        ///< China
    E_TAIWAN,                       ///< Taiwan
    E_BRAZIL,                       ///< Brazil
    /* ATSC Country Start */
    E_CANADA,                       ///< Canada
    E_MEXICO,                       ///< Mexico
    E_US,                           ///< United States
    E_SOUTHKOREA,                    ///< South Korea
    /* ATSC Country End */
    E_FIJI, // /< Fiji
    E_UZBEK, // /< Uzbek
    E_TAJIKISTAN, // /< Tajikistan
    E_ETHIOPIA, // /< Ethiopia
    E_AZERBAIJAN, // /< Azerbaijan
    E_SOUTHAFRICA, // /< South Africa
    E_ALGERIA, // /< Algeria
    E_EGYPT, // /< Egypt
    E_SAUDI_ARABIA, // /< Saudi Arabia
    E_IRAN, // /< Iran
    E_IRAQ, // /< Iraq
    E_NAMIBIA, // /< Namibia
    E_JORDAN, // /< Jordan
    E_KUWAIT, // /< Kuwait
    E_INDONESIA, // /< Indonesia
    E_ISRAEL, // /< Israel
    E_QATAR, // /< Qatar
    E_NIGERIA, // /< Nigeria
    E_ZEMBABWE, // /< Zimbabwe
    E_LITHUANIA, // /< Lithuania
    E_MOROCCO, // /< Morocco
    E_TUNIS, // /< Tunis
    E_INDIA, // /< India
    E_VIETNAM, // /< Vietnam
    E_HONGKONG, //< Hongkong
    E_COLOMBIA, //< Colombia
    E_MALAYSIA, //< Malaysia
    E_SINGAPORE, //< Singapore
    E_UKRAINE, //< Ukraine
    E_PAKISTAN, //< Pakistan
    E_MACEDONIA, //< Macedonia
    E_OTHERS,                       ///< Others
    // ------------------------------------
    E_COUNTRY_NUM,

} MEMBER_COUNTRY;
typedef enum
{
    E_CN_OTHERS             =   0x00,   //others,sort with servic_id

    //Beijing
    E_CN_BEIJING_GEHUA_CABLE,
    //An'hui provice
    E_CN_ANHUI_PROVINCE_CABLE,
    E_CN_HEFEI_CABEL,
    E_CN_ANQING_CABLE,
    E_CN_BENGBU_CABLE,
    //Fujian provice
    E_CN_XIAMEN_PROVINCE_CABLE,
    E_CN_QUANZHOU_CABLE,
    E_CN_LONGYAN_CABLE,
    E_CN_ZHANGZHOU_CABLE,
    //Gansu provice
    //Guangdong provice
    E_CN_GUANGZHOU_ZHUJIANG_CABLE,
    E_CN_GUANGZHOU_PROVINCE_CABLE,
    E_CN_DONGGUAN_CABLE,
    //Guangxi provice
    //Guizhou provice
    E_CN_GUIYANG_PROVINCE_CABLE,
    //Hainan provice
    E_CN_HAIKOU_CABEL,
    //Hebei provice
    E_CN_SHIJIAZHUANG_CABEL,
    E_CN_QINHUANGDAO_CABLE,
    E_CN_TANGSHAN_CABLE,
    //Heilongjiang provice
    E_CN_HAERBIN_CABLE,
    //Henan provice
    E_CN_ZHENGZHOU_CABLE,
    E_CN_LUOYANG_CABLE,
    E_CN_NANYANG_CABLE,
    //Hubei provice
    E_CN_HUBEI_CHUTIAN_CABLE,
    E_CN_WUHAN_CABLE,
    E_CN_HUANGGANG_CABLE,
    E_CN_JINGZHOU_CABLE,
    E_CN_YICHANG_CABLE,
    //Hunan provice
    E_CN_CHANGSHA_GUANGDA_CABLE,
    E_CN_CHANGSHA_GUOAN_CABLE,
    //Jiangsu provice
    E_CN_NANTONG_CABLE,
    //Jiangxi provice
    E_CN_NANCHANG_CABEL,
    //Jilin provice
    E_CN_JILIN_PROVINCE_CABLE,
    //Liaoning provice
    E_CN_DALIAN_CABLE,
    //Neimenggu provice
    E_CN_HUHEHAOTE_CABLE,
    //Ningxia provice
    //Qinghai provice
    //Shangdong provice
    //Shangxi provice
    E_CN_XIAN_CABLE,
    //Shanxi provice
    //Sichuan provice
    E_CN_CHENGDU_XING_CABLE,
    //Xinjiang provice
    E_CN_WULUMUQI_CABLE,
    //Zhejiang provice
    E_CN_JINHUA_CABLE,
    E_CN_NINGBO_CABEL,
    E_CN_SHAOXING_CABLE,
    E_CN_MIANYANG_CABLE,
    E_CN_HUBEI_SHIYAN,
    E_CN_YANCHENG_YOUXIAN,
    E_CN_CHENGDU_CHENGHUAQU,
    E_CN_HUBEI_DANJIANG,
    E_CN_YANGZHOU_CABLE,
    E_CN_MAANSHAN_CABLE,
    E_CN_QINGDAO_CABLE,
    //ShangHai
    E_CN_SHANGHAI_OCN_CABLE,

    E_CN_NUM,
}E_CHINA_DVBCREGION;

typedef enum
{
    EN_CABLEOP_OTHER   = 0,
    EN_CABLEOP_CDSMATV,
    EN_CABLEOP_CDCABLE,
    EN_CABLEOP_COMHEM,
    EN_CABLEOP_UPC,
    EN_CABLEOP_YOUSEE,
    EN_CABLEOP_CABLEREADY,
    EN_CABLEOP_ZIGGO,
    EN_CABLEOP_STOFA,
    EN_CABLEOP_NUMERICABLE,
    EN_CABLEOP_UNITYMEDIA,
    EN_CABLEOP_TELENET,
    EN_CABLEOP_KDG,
    // -------------------------------------
    EN_CABLEOP_NUM,
}EN_CABLE_OPERATORS;

typedef enum
{
    EN_SATEPF_OTHER = 0,
    EN_SATEPF_HDPLUS,
    EN_SATEPF_FREESAT,
    EN_SATEPF_DIGITURK,
    EN_SATEPF_MAX,
}EN_SATELLITE_PLATFORM;
typedef enum//ISO 639: 3-letter codes
{
    E_LANGUAGE_CZECH,
    E_LANGUAGE_CHAMIC,
    E_LANGUAGE_DANISH,
    E_LANGUAGE_DARGWA,
    E_LANGUAGE_LANDDAYAK,
    E_LANGUAGE_GERMAN,
    E_LANGUAGE_ENGLISH,
    E_LANGUAGE_SPANISH,
    E_LANGUAGE_GREEK,
    E_LANGUAGE_FRENCH,
    E_LANGUAGE_CROATIAN,
    E_LANGUAGE_SORBIANUPPER,
    E_LANGUAGE_ITALIAN,
    E_LANGUAGE_HUNGARIAN,
    E_LANGUAGE_DUTCH,
    E_LANGUAGE_NORWEGIAN,
    E_LANGUAGE_POLISH,
    E_LANGUAGE_PORTUGUESE,
    E_LANGUAGE_RUSSIAN,
    E_LANGUAGE_ROMANIAN,
    E_LANGUAGE_SLOVENIAN,
    E_LANGUAGE_SERBIAN,
    E_LANGUAGE_FINNISH,
    E_LANGUAGE_SWEDISH,
    E_LANGUAGE_BULGARIAN,
    E_LANGUAGE_SLOVAK,
    E_LANGUAGE_CHINESE,
    E_LANGUAGE_CHUUKESE,
    E_LANGUAGE_GAELIC,
    E_LANGUAGE_GBAYA,
    E_LANGUAGE_WELSH,
    E_LANGUAGE_ARABIC,
    E_LANGUAGE_IRISH,
    E_LANGUAGE_AFRIKAANS,
    E_LANGUAGE_XHOSA,
    E_LANGUAGE_ZULU,
    E_LANGUAGE_LATVIAN,
    E_LANGUAGE_HEBREW,
    E_LANGUAGE_TURKISH,
    E_LANGUAGE_ESTONIAN,
    E_LANGUAGE_NETHERLANDS,//no in ISO639
    E_LANGUAGE_KOREAN,
    E_LANGUAGE_KOSRAEAN,
    E_LANGUAGE_HINDI,
    E_LANGUAGE_HITTITE,
    E_LANGUAGE_HMONG,
    E_LANGUAGE_MANDARIN,//no in ISO639
    E_LANGUAGE_CANTONESE,//no in ISO639
    E_LANGUAGE_MAORI,
    E_LANGUAGE_QAA,//no in ISO639
    E_LANGUAGE_UNDETERMINED,//**-- Italy CI Certificate --**//
    E_LANGUAGE_AD,//**-- AD language --**//
    E_LANGUAGE_UNKNOWN,       //move to hear to avoid haveing same value as spanish.
    E_LANGUAGE_NONE,          //move to hear to avoid haveing same value as spanish.

    E_LANGUAGE_ABKHAZIAN,
    E_LANGUAGE_ACHINESE,
    E_LANGUAGE_ACOLI,
    E_LANGUAGE_ADANGME,
    E_LANGUAGE_ADYGHE,
    E_LANGUAGE_AFAR,
    E_LANGUAGE_AFRIHILI,
    E_LANGUAGE_AFRO,
    E_LANGUAGE_AINU,
    E_LANGUAGE_AKAN,
    E_LANGUAGE_AKKADIAN,
    E_LANGUAGE_ALBANIAN,
    E_LANGUAGE_ALEUT,
    E_LANGUAGE_ALGONQUIAN,
    E_LANGUAGE_ALTAISOUTHERN,
    E_LANGUAGE_ALTAIC,
    E_LANGUAGE_AMHARIC,
    E_LANGUAGE_APACHE,
    E_LANGUAGE_ARAMAIC,
    E_LANGUAGE_ARAGONESE,
    E_LANGUAGE_ARAPAHO,
    E_LANGUAGE_ARAUCANIAN,
    E_LANGUAGE_ARAWAK,
    E_LANGUAGE_ARMENIAN,
    E_LANGUAGE_ARTIFICIAL,
    E_LANGUAGE_ASSAMESE,
    E_LANGUAGE_ASTURIAN,
    E_LANGUAGE_ATHAPASCAN,
    E_LANGUAGE_AUSTRONESIAN,
    E_LANGUAGE_AUSTRALIAN,
    E_LANGUAGE_AVARIC,
    E_LANGUAGE_AVESTAN,
    E_LANGUAGE_AWADHI,
    E_LANGUAGE_AYMARA,
    E_LANGUAGE_AZERBAIJANI,
    E_LANGUAGE_AZTEC,
    E_LANGUAGE_BALINESE,
    E_LANGUAGE_BALTIC,
    E_LANGUAGE_BALUCHI,
    E_LANGUAGE_BAMBARA,
    E_LANGUAGE_BAMILEKE,
    E_LANGUAGE_BANDA,
    E_LANGUAGE_BANTU,
    E_LANGUAGE_BASA,
    E_LANGUAGE_BASHKIR,
    E_LANGUAGE_BASQUE,
    E_LANGUAGE_BEJA,
    E_LANGUAGE_BEMBA,
    E_LANGUAGE_BENGALI,
    E_LANGUAGE_BERBER,
    E_LANGUAGE_BHOJPURI,
    E_LANGUAGE_BIHARI,
    E_LANGUAGE_BIKOL,
    E_LANGUAGE_BINI,
    E_LANGUAGE_BISLAMA,
    E_LANGUAGE_BOSNIAN,
    E_LANGUAGE_BRAJ,
    E_LANGUAGE_BRETON,
    E_LANGUAGE_BUGINESE,
    E_LANGUAGE_BURIAT,
    E_LANGUAGE_BURMESE,
    E_LANGUAGE_BLIN,
    E_LANGUAGE_BYELORUSSIAN,
    E_LANGUAGE_CADDO,
    E_LANGUAGE_CARIB,
    E_LANGUAGE_CATALAN,
    E_LANGUAGE_CAUCASIAN,
    E_LANGUAGE_CEBUANO,
    E_LANGUAGE_CELTIC,
    E_LANGUAGE_CENTRALAMERICANINDIAN,
    E_LANGUAGE_CHAGATAI,
    E_LANGUAGE_CHAMORRO,
    E_LANGUAGE_CHECHEN,
    E_LANGUAGE_CHEROKEE,
    E_LANGUAGE_CHEYENNE,
    E_LANGUAGE_CHIBCHA,
    E_LANGUAGE_CHINOOKJARGON,
    E_LANGUAGE_CHOCTAW,
    E_LANGUAGE_CHIPEWYAN,
    E_LANGUAGE_CHURCHSLAVIC,
    E_LANGUAGE_CHUVASH,
    E_LANGUAGE_COPTIC,
    E_LANGUAGE_CORNISH,
    E_LANGUAGE_CORSICAN,
    E_LANGUAGE_CREE,
    E_LANGUAGE_CREEK,
    E_LANGUAGE_CREOLESANDPIDGINS,
    E_LANGUAGE_CRIMEANTATAR,
    E_LANGUAGE_CREOLESANDPIDGINSENGLISH,
    E_LANGUAGE_CREOLESANDPIDGINSFRENCH,
    E_LANGUAGE_CREOLESANDPIDGINSPORTUGUESE,
    E_LANGUAGE_KASHUBIAN,
    E_LANGUAGE_CUSHITIC,
    E_LANGUAGE_DAKOTA,
    E_LANGUAGE_DELAWARE,
    E_LANGUAGE_SLAVEY,
    E_LANGUAGE_DOGRIB,
    E_LANGUAGE_DHIVEHI,
    E_LANGUAGE_DINKA,
    E_LANGUAGE_DIVEHI,
    E_LANGUAGE_DOGRI,
    E_LANGUAGE_DRAVIDIAN,
    E_LANGUAGE_SORBIANLOWER,
    E_LANGUAGE_DUALA,
    E_LANGUAGE_DUTCHMIDDLE,
    E_LANGUAGE_DYULA,
    E_LANGUAGE_DZONGKHA,
    E_LANGUAGE_EFIK,
    E_LANGUAGE_EGYPTIAN,
    E_LANGUAGE_EKAJUK,
    E_LANGUAGE_ELAMITE,
    E_LANGUAGE_ENGLISHMIDDLE,
    E_LANGUAGE_ENGLISHOLD,
    E_LANGUAGE_ANGIKA,
    E_LANGUAGE_ESKIMO,
    E_LANGUAGE_ESPERANTO,
    E_LANGUAGE_EWE,
    E_LANGUAGE_EWONDO,
    E_LANGUAGE_FANG,
    E_LANGUAGE_FANTI,
    E_LANGUAGE_FAROESE,
    E_LANGUAGE_FIJIAN,
    E_LANGUAGE_FILIPINO,
    E_LANGUAGE_FINNOUGRIAN,
    E_LANGUAGE_FON,
    E_LANGUAGE_FRENCHMIDDLE,
    E_LANGUAGE_FRENCHOLD,
    E_LANGUAGE_FRISIANNORTHERN,
    E_LANGUAGE_FRISIANEASTERN,
    E_LANGUAGE_FRISIAN,
    E_LANGUAGE_FULAH,
    E_LANGUAGE_FRIULIAN,
    E_LANGUAGE_GA,
    E_LANGUAGE_GALLEGAN,
    E_LANGUAGE_GANDA,
    E_LANGUAGE_GAYO,
    E_LANGUAGE_GEEZ,
    E_LANGUAGE_GEORGIAN,
    E_LANGUAGE_GERMANMIDDLEHIGH,
    E_LANGUAGE_GERMANOLDHIGH,
    E_LANGUAGE_GORONTALO,
    E_LANGUAGE_GERMANIC,
    E_LANGUAGE_GILBERTESE,
    E_LANGUAGE_GONDI,
    E_LANGUAGE_GOTHIC,
    E_LANGUAGE_GREBO,
    E_LANGUAGE_GREEKANCIENT,
    E_LANGUAGE_GREENLANDIC,
    E_LANGUAGE_GUARANI,
    E_LANGUAGE_SWISSGERMAN,
    E_LANGUAGE_GUJARATI,
    E_LANGUAGE_GWICHIN,
    E_LANGUAGE_HAIDA,
    E_LANGUAGE_HAITIANCREOLE,
    E_LANGUAGE_HAUSA,
    E_LANGUAGE_HAWAIIAN,
    E_LANGUAGE_HERERO,
    E_LANGUAGE_HILIGAYNON,
    E_LANGUAGE_HIMACHALI,
    E_LANGUAGE_HIRIMOTU,
    E_LANGUAGE_HUPA,
    E_LANGUAGE_IBAN,
    E_LANGUAGE_ICELANDIC,
    E_LANGUAGE_IDO,
    E_LANGUAGE_NUOSU,
    E_LANGUAGE_IGBO,
    E_LANGUAGE_IJO,
    E_LANGUAGE_ILOKO,
    E_LANGUAGE_INDIC,
    E_LANGUAGE_INDOEUROPEAN,
    E_LANGUAGE_INGUSH,
    E_LANGUAGE_INDONESIAN,
    E_LANGUAGE_INTERLINGUA,
    E_LANGUAGE_INTERLINGUE,
    E_LANGUAGE_INUKTITUT,
    E_LANGUAGE_INUPIAK,
    E_LANGUAGE_IRANIAN,
    E_LANGUAGE_IRISHOLD,
    E_LANGUAGE_IRISHMIDDLE,
    E_LANGUAGE_IROQUOIAN,
    E_LANGUAGE_JAPANESE,
    E_LANGUAGE_JAVANESE,
    E_LANGUAGE_LOJBAN,
    E_LANGUAGE_JUDEOARABIC,
    E_LANGUAGE_JUDEOPERSIAN,
    E_LANGUAGE_KABYLE,
    E_LANGUAGE_KACHIN,
    E_LANGUAGE_KAMBA,
    E_LANGUAGE_KANNADA,
    E_LANGUAGE_KANURI,
    E_LANGUAGE_KARAKALPAK,
    E_LANGUAGE_KAREN,
    E_LANGUAGE_KASHMIRI,
    E_LANGUAGE_KAWI,
    E_LANGUAGE_KAZAKH,
    E_LANGUAGE_CIRCASSIAN,
    E_LANGUAGE_KHASI,
    E_LANGUAGE_KHMER,
    E_LANGUAGE_KHOISAN,
    E_LANGUAGE_KHOTANESE,
    E_LANGUAGE_KIKUYU,
    E_LANGUAGE_KINYARWANDA,
    E_LANGUAGE_KIRGHIZ,
    E_LANGUAGE_KIMBUNDU,
    E_LANGUAGE_KOMI,
    E_LANGUAGE_KONGO,
    E_LANGUAGE_KONKANI,
    E_LANGUAGE_KPELLE,
    E_LANGUAGE_KARACHAYBALKAR,
    E_LANGUAGE_KARELIAN,
    E_LANGUAGE_KRU,
    E_LANGUAGE_KUANYAMA,
    E_LANGUAGE_KUMYK,
    E_LANGUAGE_KURDISH,
    E_LANGUAGE_KURUKH,
    E_LANGUAGE_KUSAIE,
    E_LANGUAGE_KUTENAI,
    E_LANGUAGE_LADINO,
    E_LANGUAGE_LAHNDA,
    E_LANGUAGE_LAMBA,
    E_LANGUAGE_LANGUE,
    E_LANGUAGE_LAO,
    E_LANGUAGE_LATIN,
    E_LANGUAGE_LETZEBURGESCH,
    E_LANGUAGE_LEZGHIAN,
    E_LANGUAGE_LIMBURGISH,
    E_LANGUAGE_LINGALA,
    E_LANGUAGE_LITHUANIAN,
    E_LANGUAGE_LOZI,
    E_LANGUAGE_LUBALULUA,
    E_LANGUAGE_LUBAKATANGA,
    E_LANGUAGE_LUISENO,
    E_LANGUAGE_LUNDA,
    E_LANGUAGE_LUO,
    E_LANGUAGE_LUSHAI,
    E_LANGUAGE_MACEDONIAN,
    E_LANGUAGE_MADURESE,
    E_LANGUAGE_MAGAHI,
    E_LANGUAGE_MAITHILI,
    E_LANGUAGE_MAKASAR,
    E_LANGUAGE_MALAGASY,
    E_LANGUAGE_MALAY,
    E_LANGUAGE_MOKSHA,
    E_LANGUAGE_MANDAR,
    E_LANGUAGE_MALAYALAM,
    E_LANGUAGE_MALTESE,
    E_LANGUAGE_MANCHU,
    E_LANGUAGE_MANDINGO,
    E_LANGUAGE_MANIPURI,
    E_LANGUAGE_MANOBO,
    E_LANGUAGE_MANX,
    E_LANGUAGE_MARATHI,
    E_LANGUAGE_MARI,
    E_LANGUAGE_MARSHALL,
    E_LANGUAGE_MIRANDESE,
    E_LANGUAGE_MARWARI,
    E_LANGUAGE_MASAI,
    E_LANGUAGE_MAYAN,
    E_LANGUAGE_ERZYA,
    E_LANGUAGE_MENDE,
    E_LANGUAGE_MICMAC,
    E_LANGUAGE_MINANGKABAU,
    E_LANGUAGE_MISCELLANEOUS,
    E_LANGUAGE_MOHAWK,
    E_LANGUAGE_MOLDAVIAN,
    E_LANGUAGE_MONKMER,
    E_LANGUAGE_MONGO,
    E_LANGUAGE_MONGOLIAN,
    E_LANGUAGE_MOSSI,
    E_LANGUAGE_MULTIPLE,
    E_LANGUAGE_MUNDA,
    E_LANGUAGE_NEAPOLITAN,
    E_LANGUAGE_NAURU,
    E_LANGUAGE_NAVAJO,
    E_LANGUAGE_NDEBELENORTH,
    E_LANGUAGE_NDEBELESOUTH,
    E_LANGUAGE_NDONGO,
    E_LANGUAGE_GERMANLOW,
    E_LANGUAGE_NEPALI,
    E_LANGUAGE_NEWARI,
    E_LANGUAGE_NIAS,
    E_LANGUAGE_NIGERKORDOFANIAN,
    E_LANGUAGE_NILOSAHARAN,
    E_LANGUAGE_NIUEAN,
    E_LANGUAGE_NORWEGIANBOKMAL,
    E_LANGUAGE_NOGAI,
    E_LANGUAGE_NORSEOLD,
    E_LANGUAGE_NORTHAMERICANINDIAN,
    E_LANGUAGE_NORWEGIANNYNORSK,
    E_LANGUAGE_NUBIAN,
    E_LANGUAGE_NYAMWEZI,
    E_LANGUAGE_NEWARICLASSICAL,
    E_LANGUAGE_NYANJA,
    E_LANGUAGE_NYANKOLE,
    E_LANGUAGE_NYORO,
    E_LANGUAGE_NZIMA,
    E_LANGUAGE_OJIBWA,
    E_LANGUAGE_ORIYA,
    E_LANGUAGE_OROMO,
    E_LANGUAGE_OSAGE,
    E_LANGUAGE_OSSETIC,
    E_LANGUAGE_OTOMIAN,
    E_LANGUAGE_PAHLAVI,
    E_LANGUAGE_PALAUAN,
    E_LANGUAGE_PALI,
    E_LANGUAGE_PAMPANGA,
    E_LANGUAGE_PANGASINAN,
    E_LANGUAGE_PANJABI,
    E_LANGUAGE_PAPIAMENTO,
    E_LANGUAGE_PAPUANAUSTRALIAN,
    E_LANGUAGE_PERSIAN,
    E_LANGUAGE_PERSIANOLD,
    E_LANGUAGE_PHOENICIAN,
    E_LANGUAGE_PHILIPPINE,
    E_LANGUAGE_PONAPE,
    E_LANGUAGE_PRAKRIT,
    E_LANGUAGE_PROVENCALOLD,
    E_LANGUAGE_PUSHTO,
    E_LANGUAGE_QUECHUA,
    E_LANGUAGE_RHAETOROMANCE,
    E_LANGUAGE_RAJASTHANI,
    E_LANGUAGE_RAPANUI,
    E_LANGUAGE_RAROTONGAN,
    E_LANGUAGE_ROMANCE,
    E_LANGUAGE_ROMANY,
    E_LANGUAGE_RUNDI,
    E_LANGUAGE_AROMANIAN,
    E_LANGUAGE_SALISHAN,
    E_LANGUAGE_SAMARITANARAMAIC,
    E_LANGUAGE_SAMISOUTHERN,
    E_LANGUAGE_SAMINORTHERN,
    E_LANGUAGE_SAMI,
    E_LANGUAGE_LULESAMI,
    E_LANGUAGE_INARISAMI,
    E_LANGUAGE_SAMOAN,
    E_LANGUAGE_SKOLTSAMI,
    E_LANGUAGE_SANDAWE,
    E_LANGUAGE_SANGO,
    E_LANGUAGE_SANSKRIT,
    E_LANGUAGE_SARDINIAN,
    E_LANGUAGE_SASAK,
    E_LANGUAGE_SANTALI,
    E_LANGUAGE_SICILIAN,
    E_LANGUAGE_SCOTS,
    E_LANGUAGE_SELKUP,
    E_LANGUAGE_SEMITIC,
    E_LANGUAGE_SRANANTONGO,
    E_LANGUAGE_SERBOCROATIAN,
    E_LANGUAGE_SERER,
    E_LANGUAGE_SIGN,
    E_LANGUAGE_SHAN,
    E_LANGUAGE_SHONA,
    E_LANGUAGE_SIDAMO,
    E_LANGUAGE_SIKSIKA,
    E_LANGUAGE_SINDHI,
    E_LANGUAGE_SONINKE,
    E_LANGUAGE_SINGHALESE,
    E_LANGUAGE_SINOTIBETAN,
    E_LANGUAGE_SIOUAN,
    E_LANGUAGE_SLAVIC,
    E_LANGUAGE_SISWANT,
    E_LANGUAGE_SOGDIAN,
    E_LANGUAGE_SOMALI,
    E_LANGUAGE_SONGHAI,
    E_LANGUAGE_SORBIAN,
    E_LANGUAGE_WALLOON,
    E_LANGUAGE_NKO,
    E_LANGUAGE_SOTHONORTHERN,
    E_LANGUAGE_SOTHOSOUTHERN,
    E_LANGUAGE_SOUTHAMERICANINDIAN,
    E_LANGUAGE_SUKUMA,
    E_LANGUAGE_SUMERIAN,
    E_LANGUAGE_SUDANESE,
    E_LANGUAGE_SUSU,
    E_LANGUAGE_SWAHILI,
    E_LANGUAGE_SWAZI,
    E_LANGUAGE_SWIZE,
    E_LANGUAGE_SYRIACCLASSICAL,
    E_LANGUAGE_SYRIAC,
    E_LANGUAGE_TAGALOG,
    E_LANGUAGE_TAHITIAN,
    E_LANGUAGE_TETUM,
    E_LANGUAGE_TAJIK,
    E_LANGUAGE_TAMASHEK,
    E_LANGUAGE_TAI,
    E_LANGUAGE_TAMIL,
    E_LANGUAGE_TATAR,
    E_LANGUAGE_TELETEXT,
    E_LANGUAGE_TELUGU,
    E_LANGUAGE_TERENO,
    E_LANGUAGE_THAI,
    E_LANGUAGE_TIBETAN,
    E_LANGUAGE_TIGRE,
    E_LANGUAGE_TIGRINYA,
    E_LANGUAGE_TIMNE,
    E_LANGUAGE_TIVI,
    E_LANGUAGE_KLINGON,
    E_LANGUAGE_TOKELAU,
    E_LANGUAGE_TLINGIT,
    E_LANGUAGE_TONGANYASA,
    E_LANGUAGE_TONGAISLANDS,
    E_LANGUAGE_TRUK,
    E_LANGUAGE_TOKPISIN,
    E_LANGUAGE_TSIMSHIAN,
    E_LANGUAGE_TSONGA,
    E_LANGUAGE_TSWANA,
    E_LANGUAGE_TUMBUKA,
    E_LANGUAGE_TUPIAN,
    E_LANGUAGE_TURKISHOTTOMAN,
    E_LANGUAGE_TURKMEN,
    E_LANGUAGE_TUVINIAN,
    E_LANGUAGE_TUVALU,
    E_LANGUAGE_TWI,
    E_LANGUAGE_UDMURT,
    E_LANGUAGE_UGARITIC,
    E_LANGUAGE_UIGHUR,
    E_LANGUAGE_UKRAINIAN,
    E_LANGUAGE_UMBUNDU,
    E_LANGUAGE_URDU,
    E_LANGUAGE_UZBEK,
    E_LANGUAGE_VAI,
    E_LANGUAGE_VENDA,
    E_LANGUAGE_VIETNAMESE,
    E_LANGUAGE_VOLAPUK,
    E_LANGUAGE_VOTIC,
    E_LANGUAGE_WAKASHAN,
    E_LANGUAGE_WALAMO,
    E_LANGUAGE_WARAY,
    E_LANGUAGE_WASHO,
    E_LANGUAGE_WOLOF,
    E_LANGUAGE_KALMYK,
    E_LANGUAGE_YAKUT,
    E_LANGUAGE_YAO,
    E_LANGUAGE_YAP,
    E_LANGUAGE_YIDDISH,
    E_LANGUAGE_YORUBA,
    E_LANGUAGE_YUPIK,
    E_LANGUAGE_ZAPOTEC,
    E_LANGUAGE_BLISSYMBOLICS,
    E_LANGUAGE_ZENAGA,
    E_LANGUAGE_ZHUANG,
    E_LANGUAGE_ZANDE,
    E_LANGUAGE_ZUNI,
    E_LANGUAGE_ZAZAKI,
    E_LANGUAGE_VALENCIAN,
    E_LANGUAGE_NUM,           //Language maximum
    E_LANGUAGE_MAX = 0xFFFF
} MEMBER_LANGUAGE;

typedef enum
{
    // GMT
    TIMEZONE_GMT_0_START,
    TIMEZONE_CANARY = TIMEZONE_GMT_0_START,
    TIMEZONE_MONTEVIDEO,
    TIMEZONE_LIMA,
    //TIMEZONE_BUENOS_AIRES,
    TIMEZONE_SANTIAGO,
    TIMEZONE_CARACAS,
    TIMEZONE_QUITO,
    TIMEZONE_SAN_JOSE,
    TIMEZONE_ASUNCION,
    TIMEZONE_LA_PAZ,
    TIMEZONE_BELMOPAN,
    TIMEZONE_MANAGUA,
    TIMEZONE_GUATEMALA,
    TIMEZONE_LISBON,
    TIMEZONE_DUBLIN,
    TIMEZONE_LONDON,
    TIMEZONE_RABAT,
    TIMEZONE_GMT_0_END = TIMEZONE_RABAT,

    // GMT + 0.5
    TIMEZONE_GMT_0Point5_START,
    TIMEZONE_GMT_0Point5_END = TIMEZONE_GMT_0Point5_START,

    // GMT + 1
    TIMEZONE_GMT_1_START,
    TIMEZONE_AMSTERDAM = TIMEZONE_GMT_1_START,
    TIMEZONE_BEOGRAD,
    TIMEZONE_BERLIN,
    TIMEZONE_BERN,
    TIMEZONE_BRATISLAVA,
    TIMEZONE_BRUSSELS,
    TIMEZONE_BUDAPEST,
    TIMEZONE_COPENHAGEN,
    TIMEZONE_GENEVA,
    TIMEZONE_LIUBLJANA,
    TIMEZONE_LUXEMBOURG,
    TIMEZONE_MADRID,
    TIMEZONE_OSLO,
    TIMEZONE_PARIS,
    TIMEZONE_PRAGUE,
    TIMEZONE_ROME,
    TIMEZONE_STOCKHOLM,
    TIMEZONE_WARSAW,
    TIMEZONE_VIENNA,
    TIMEZONE_ZAGREB,
    TIMEZONE_ALGIERS,
    TIMEZONE_LAGOS,
    TIMEZONE_SKOPJE,
    TIMEZONE_TUNIS,
    TIMEZONE_GMT_1_END = TIMEZONE_TUNIS,

    // GMT + 1.5
    TIMEZONE_GMT_1Point5_START,
    TIMEZONE_GMT_1Point5_END = TIMEZONE_GMT_1Point5_START,

    // GMT + 2
    TIMEZONE_GMT_2_START,
    TIMEZONE_ATHENS = TIMEZONE_GMT_2_START,
    TIMEZONE_BUCURESTI,
    TIMEZONE_HELSINKI,
    TIMEZONE_ISTANBUL,
    TIMEZONE_SOFIA,
    TIMEZONE_TALLINN,
    TIMEZONE_VILNIUS,
    TIMEZONE_JERUSALEM,
    TIMEZONE_JOHANNESBURG,
    TIMEZONE_CAIRO,
    TIMEZONE_WINDHOEK,
    TIMEZONE_AMMAN,
    TIMEZONE_KYIV,
    TIMEZONE_HARARE,
    TIMEZONE_GMT_2_END = TIMEZONE_HARARE,

    // GMT + 2.5
    TIMEZONE_GMT_2Point5_START,
    TIMEZONE_GMT_2Point5_END = TIMEZONE_GMT_2Point5_START,

    // GMT + 3
    TIMEZONE_GMT_3_START,
    TIMEZONE_MOSCOW = TIMEZONE_GMT_3_START,
    TIMEZONE_ADDIS_ABABA,
    TIMEZONE_RIYADH,
    TIMEZONE_BAGHDAD,
    TIMEZONE_KUWAIT,
    TIMEZONE_DOHA,
    TIMEZONE_GMT_3_END = TIMEZONE_DOHA,

    // GMT + 3.5
    TIMEZONE_GMT_3Point5_START,
    TIMEZONE_TEHERAN = TIMEZONE_GMT_3Point5_START,
    TIMEZONE_GMT_3Point5_END = TIMEZONE_TEHERAN,

    //GMT + 4
    TIMEZONE_GMT_4_START,
    TIMEZONE_DUBAI = TIMEZONE_GMT_4_START,
    TIMEZONE_BAKU,
    TIMEZONE_GMT_4_END = TIMEZONE_BAKU,

    //GMT + 4.5
    TIMEZONE_GMT_4Point5_START,
    TIMEZONE_KABUL = TIMEZONE_GMT_4Point5_START,
    TIMEZONE_GMT_4Point5_END = TIMEZONE_KABUL,

    //GMT + 5
    TIMEZONE_GMT_5_START,
    TIMEZONE_URAL = TIMEZONE_GMT_5_START,
    TIMEZONE_MALE,
    TIMEZONE_TASHKENT,
    TIMEZONE_ISLAMABAD,
    TIMEZONE_DUSHANBE,
    TIMEZONE_GMT_5_END = TIMEZONE_DUSHANBE,

    //GMT + 5.5
    TIMEZONE_GMT_5Point5_START,
    TIMEZONE_CALCUTTA = TIMEZONE_GMT_5Point5_START,
    TIMEZONE_NEWDELHI,
    TIMEZONE_GMT_5Point5_END = TIMEZONE_NEWDELHI,

    //GMT + 5.45
    TIMEZONE_GMT_5Point45_START,
    TIMEZONE_KATHMANDU = TIMEZONE_GMT_5Point45_START,
    TIMEZONE_GMT_5Point45_END = TIMEZONE_KATHMANDU,

    //GMT + 6
    TIMEZONE_GMT_6_START,
    TIMEZONE_ALMAATA = TIMEZONE_GMT_6_START,
    TIMEZONE_GMT_6_END = TIMEZONE_ALMAATA,

    //GMT + 6.5
    TIMEZONE_GMT_6Point5_START,
    TIMEZONE_YANGON = TIMEZONE_GMT_6Point5_START,
    TIMEZONE_GMT_6Point5_END = TIMEZONE_YANGON,

    //GMT + 7
    TIMEZONE_GMT_7_START,
    TIMEZONE_BANGKOK = TIMEZONE_GMT_7_START,
    TIMEZONE_HANOI,
    TIMEZONE_JAKARTA,
    TIMEZONE_GMT_7_END = TIMEZONE_JAKARTA,

    // GMT + 7.5
    TIMEZONE_GMT_7Point5_START,
    TIMEZONE_GMT_7Point5_END = TIMEZONE_GMT_7Point5_START,

    //GMT + 8
    TIMEZONE_GMT_8_START,
    TIMEZONE_WA = TIMEZONE_GMT_8_START,
    TIMEZONE_BEIJING,
    TIMEZONE_HONGKONG,
    TIMEZONE_TAIPEI,
    TIMEZONE_KUALALUMPUR,
    TIMEZONE_SINGAPORE,
    TIMEZONE_DAVAO,
    TIMEZONE_GMT_8_END = TIMEZONE_DAVAO,

    // GMT + 8.5
    TIMEZONE_GMT_8Point5_START,
    TIMEZONE_GMT_8Point5_END = TIMEZONE_GMT_8Point5_START,

    //GMT + 9
    TIMEZONE_GMT_9_START,
    TIMEZONE_TOKYO = TIMEZONE_GMT_9_START,
    TIMEZONE_SEOUL,
    TIMEZONE_GMT_9_END = TIMEZONE_SEOUL,

    //GMT + 9.5
    TIMEZONE_GMT_9Point5_START,
    TIMEZONE_SA = TIMEZONE_GMT_9Point5_START,
    TIMEZONE_NT,
    TIMEZONE_GMT_9Point5_END = TIMEZONE_NT,

    //GMT + 10
    TIMEZONE_GMT_10_START,
    TIMEZONE_NSW = TIMEZONE_GMT_10_START,
    TIMEZONE_VIC,
    TIMEZONE_QLD,
    TIMEZONE_TAS,
    TIMEZONE_GMT_10_END = TIMEZONE_TAS,

    //GMT + 10.5
    TIMEZONE_GMT_10Point5_START,
    TIMEZONE_ADLAIDE = TIMEZONE_GMT_10Point5_START,
    TIMEZONE_GMT_10Point5_END = TIMEZONE_ADLAIDE,

    //GMT + 11
    TIMEZONE_GMT_11_START,
    TIMEZONE_SYNDEY = TIMEZONE_GMT_11_START,
    TIMEZONE_GMT_11_END = TIMEZONE_SYNDEY,

    // GMT + 11.5
    TIMEZONE_GMT_11Point5_START,
    TIMEZONE_GMT_11Point5_END = TIMEZONE_GMT_11Point5_START,

    //GMT +  12
    TIMEZONE_GMT_12_START,
    TIMEZONE_NZST = TIMEZONE_GMT_12_START,
    TIMEZONE_GMT_12_END = TIMEZONE_NZST,

    // GMT + 12.5
    TIMEZONE_GMT_12Point5_START,
    TIMEZONE_GMT_12Point5_END = TIMEZONE_GMT_12Point5_START,

    //GMT +  13
    TIMEZONE_GMT_13_START,
    TIMEZONE_TONGATAPU = TIMEZONE_GMT_13_START,
    TIMEZONE_SUVA,
    TIMEZONE_GMT_13_END = TIMEZONE_SUVA,

    //GMT - 11.5
    TIMEZONE_GMT_Minus11_5_START,
    TIMEZONE_GMT_Minus11_5_END = TIMEZONE_GMT_Minus11_5_START,

    //GMT - 11
    TIMEZONE_GMT_Minus11_START,
    TIMEZONE_NORTH_AMERICA_MIDWAY = TIMEZONE_GMT_Minus11_START,
    TIMEZONE_GMT_Minus11_END = TIMEZONE_NORTH_AMERICA_MIDWAY,

    //GMT - 10.5
    TIMEZONE_GMT_Minus10_5_START,
    TIMEZONE_GMT_Minus10_5_END = TIMEZONE_GMT_Minus10_5_START,

    //GMT - 10
    TIMEZONE_GMT_Minus10_START,
    TIMEZONE_NORTH_AMERICA_HAWAIIAN = TIMEZONE_GMT_Minus10_START,
    TIMEZONE_GMT_Minus10_END = TIMEZONE_NORTH_AMERICA_HAWAIIAN,

    //GMT - 9.5
    TIMEZONE_GMT_Minus9_5_START,
    TIMEZONE_GMT_Minus9_5_END = TIMEZONE_GMT_Minus9_5_START,

    //GMT - 9
    TIMEZONE_GMT_Minus9_START,
    TIMEZONE_NORTH_AMERICA_ALASKAN = TIMEZONE_GMT_Minus9_START,
    TIMEZONE_GMT_Minus9_END = TIMEZONE_NORTH_AMERICA_ALASKAN,

    //GMT - 8.5
    TIMEZONE_GMT_Minus8_5_START,
    TIMEZONE_GMT_Minus8_5_END = TIMEZONE_GMT_Minus8_5_START,

    //GMT - 8
    TIMEZONE_GMT_Minus8_START,
    TIMEZONE_NORTH_AMERICA_PACIFIC = TIMEZONE_GMT_Minus8_START,
    TIMEZONE_GMT_Minus8_END = TIMEZONE_NORTH_AMERICA_PACIFIC,

    //GMT - 7.5
    TIMEZONE_GMT_Minus7_5_START,
    TIMEZONE_GMT_Minus7_5_END = TIMEZONE_GMT_Minus7_5_START,

    //GMT - 7
    TIMEZONE_GMT_Minus7_START,
    TIMEZONE_NORTH_AMERICA_MOUNTAIN = TIMEZONE_GMT_Minus7_START,
    TIMEZONE_GMT_Minus7_END = TIMEZONE_NORTH_AMERICA_MOUNTAIN,

    //GMT - 6.5
    TIMEZONE_GMT_Minus6_5_START,
    TIMEZONE_GMT_Minus6_5_END = TIMEZONE_GMT_Minus6_5_START,

    //GMT - 6
    TIMEZONE_GMT_Minus6_START,
    TIMEZONE_NORTH_AMERICA_CENTRAL = TIMEZONE_GMT_Minus6_START,
    TIMEZONE_MEXICO,
    TIMEZONE_GMT_Minus6_END = TIMEZONE_MEXICO,

    //GMT - 5.5
    TIMEZONE_GMT_Minus5_5_START,
    TIMEZONE_GMT_Minus5_5_END = TIMEZONE_GMT_Minus5_5_START,

    //GMT - 5
    TIMEZONE_GMT_Minus5_START,
    TIMEZONE_NORTH_AMERICA_EASTERN=TIMEZONE_GMT_Minus5_START,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_AM_WEST,
    TIMEZONE_ACRE,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_BOGOTA,
    TIMEZONE_TORONTO,
    TIMEZONE_GMT_Minus5_END = TIMEZONE_TORONTO,

    //GMT - 4.5
    TIMEZONE_GMT_Minus4_5_START,
    TIMEZONE_GMT_Minus4_5_END = TIMEZONE_GMT_Minus4_5_START,

    //GMT - 4
    TIMEZONE_GMT_Minus4_START,
    TIMEZONE_NORTH_AMERICA_ATLANTIC=TIMEZONE_GMT_Minus4_START,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_M_GROSSO,
    TIMEZONE_NORTH,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_GMT_Minus4_END = TIMEZONE_NORTH,


    //GMT - 3.5
    TIMEZONE_GMT_Minus3_5_START,
    TIMEZONE_NORTH_AMERICA_NEWFOUNDLAND=TIMEZONE_GMT_Minus3_5_START,
    TIMEZONE_GMT_Minus3_5_END = TIMEZONE_NORTH_AMERICA_NEWFOUNDLAND,

    //GMT - 3 Buenos Aires
    TIMEZONE_GMT_Minus3_START,
    TIMEZONE_BUENOS_AIRES=TIMEZONE_GMT_Minus3_START,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_BRASILIA,
    TIMEZONE_NORTHEAST,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_GMT_Minus3_END = TIMEZONE_NORTHEAST,

    //GMT - 2.5
    TIMEZONE_GMT_Minus2_5_START,
    TIMEZONE_GMT_Minus2_5_END = TIMEZONE_GMT_Minus2_5_START,

    //GMT - 2
    TIMEZONE_GMT_Minus2_START,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_F_NORONHA = TIMEZONE_GMT_Minus2_START,
    /* The UTC of Brazil ISDB-T will minus 3 hours*/
    TIMEZONE_GMT_Minus2_END = TIMEZONE_F_NORONHA,

    //GMT - 1.5
    TIMEZONE_GMT_Minus1_5_START,
    TIMEZONE_GMT_Minus1_5_END = TIMEZONE_GMT_Minus1_5_START,

    //GMT - 1
    TIMEZONE_GMT_Minus1_START,
    TIMEZONE_AZORES = TIMEZONE_GMT_Minus1_START,
    TIMEZONE_GMT_Minus1_END = TIMEZONE_AZORES,

    //GMT - 0.5
    TIMEZONE_GMT_Minus0_5_START,
    TIMEZONE_GMT_Minus0_5_END = TIMEZONE_GMT_Minus0_5_START,

    //GMT + 8.45
    TIMEZONE_GMT_8Point45_START,
    TIMEZONE_WA_EUCLA = TIMEZONE_GMT_8Point45_START,
    TIMEZONE_WA_CAIGUNA,
    TIMEZONE_WA_MADURA,
    TIMEZONE_GMT_8Point45_END = TIMEZONE_WA_MADURA,

    //GMT +  12.45
    TIMEZONE_GMT_12Point45_START,
    TIMEZONE_CHATHAM = TIMEZONE_GMT_12Point45_START,
    TIMEZONE_GMT_12Point45_END = TIMEZONE_CHATHAM,

    TIMEZONE_NUM, //TIMEZONE MAX
} EN_TIMEZONE;

typedef enum
{
    PM_MODE_STANBY      = 0x01,
    PM_MODE_SLEEP       = 0x02,
    PM_MODE_DEEPSLEEP   = 0x03,
    PM_MODE_DEFAULT     = 0xFF,
} EN_PM_MODE;

typedef enum
{
    EN_POWER_AC_BOOT,
    EN_POWER_DC_BOOT,
} EN_POWER_ON_MODE;

typedef enum
{
    E_DELIVERY_SYS_NONE = 0,
    E_DELIVERY_SYS_TDSD,
    E_DELIVERY_SYS_CDSD,
    E_DELIVERY_SYS_SDSD

} EN_DELIVERY_SYS_TYPE;

typedef enum
{
    EN_WAKEUPSRC_NONE = 0,
    EN_WAKEUPSRC_IR,
    EN_WAKEUPSRC_DVI,
    EN_WAKEUPSRC_CEC,
    EN_WAKEUPSRC_SAR,
    EN_WAKEUPSRC_SYNC,
    EN_WAKEUPSRC_RTC,
    EN_WAKEUPSRC_AVLINK,
    EN_WAKEUPSRC_UART,
    EN_WAKEUPSRC_GPIO,
} EN_WAKEUP_SOURCE;
#endif // __MAPI_TYPES_H__


