#ifndef __MANUALSCAN_TYPE_SCENE_H__
#define __MANUALSCAN_TYPE_SCENE_H__

#define SPACEFOCUS 98
enum REMOTE_TYPE
{
	REMOTE_UP,
	REMOTE_DOWN,
	REMOTE_LEFT,
	REMOTE_RIGHT,
	REMOTE_OK,
	REMOTE_NUMBER,
	REMOTE_UNKNOW,
};
#endif